### ISSUE TITLE
No keystore received

### ISSUE THREAD

**Issue by rikinindianic** [ToolsForDevs/FAST-SDK-Android#1]
When run the app it shows below error in Logcate even though "apiKey" is defined in app's gradle file.

ERROR in Logcate:
"No keystore received. Please setup or check your api key in your build.gradle".

**Comment by jonathangerbaud** [comment]
Hello,

Did you add the plugin's dependency and applied the plugin to your app's build.gradle as explained here: https://github.com/ToolsForDevs/FAST-SDK-Android/wiki/First-steps

Can you show me your build.gradle files so I can see if there is something wrong?

**Comment by rikinindianic** [comment]
Here is the build.gradle code,

apply plugin: 'com.android.application'
apply plugin: 'com.toolsfordevs.fast.gradle'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"
    defaultConfig {
        applicationId "com.indinaic.logindemo"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
   fastsdk {
        apiKey = "HIDDING_MY_KEY"
    }
}

`
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.core:core-ktx:1.0.2'
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'androidx.annotation:annotation:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    def version = "0.9.5"
    implementation "com.toolsfordevs.fast-beta:fast:$version"
    implementation "com.toolsfordevs.fast-beta:actions:$version"          // Actions plugin
    implementation "com.toolsfordevs.fast-beta:crashinfo:$version"        // Crash Info
    implementation "com.toolsfordevs.fast-beta:fileexplorer:$version"     // File Explorer plugin
    implementation "com.toolsfordevs.fast-beta:logger:$version"           // Logger plugin
    implementation "com.toolsfordevs.fast-beta:manifestexplorer:$version" // Manifest Explorer plugin
    implementation "com.toolsfordevs.fast-beta:networkexplorer:$version"  // Network Inspector plugin
    implementation "com.toolsfordevs.fast-beta:overlay:$version"          // Overlays plugin
    implementation "com.toolsfordevs.fast-beta:resourceexplorer:$version" // Resource Explorer plugin
    implementation "com.toolsfordevs.fast-beta:restart:$version"          // Restart Options plugin
    implementation "com.toolsfordevs.fast-beta:sharedprefs:$version"      // Shared Preferences Editor plugin
    implementation "com.toolsfordevs.fast-beta:sessionmanager:$version"   // Session Manager plugin
    implementation "com.toolsfordevs.fast-beta:viewinspector:$version"    // View Inspector plugin
    implementation "com.toolsfordevs.fast-beta:windowflags:$version"      // Window Flags plugin
}
 `

**Comment by jonathangerbaud** [comment]
Try to put the fastsdk { ... } block outside of the android { ... } block

**Comment by rikinindianic** [comment]
> Try to put the fastsdk { ... } block outside of the android { ... } block

Tried the same but not working, I'm still getting the same error.

**Comment by jonathangerbaud** [comment]
I think it's because you have not set yet your keystore.

Have you downloaded the companion app to do so?

=> https://github.com/ToolsForDevs/FAST-SDK-Android/wiki/First-steps#4---add-your-debugkeystore-hash
https://play.google.com/store/apps/details?id=com.toolsfordevs.companion

**Comment by rikinindianic** [comment]
> I think it's because you have not set yet your keystore.
> 
> Have you downloaded the companion app to do so?
> 
> => https://github.com/ToolsForDevs/FAST-SDK-Android/wiki/First-steps#4---add-your-debugkeystore-hash
> https://play.google.com/store/apps/details?id=com.toolsfordevs.companion

@jonathangerbaud I have followed all the stpes metioned along with companion app. I have already installed companion app and I have also edited the hash in companion app by selecting my application. I've followed every steps but nothing worked, I also want to tell you that some of my friends also have tried but none of them got success.

I would like you to go ahead and perform the same steps as mentioned in below page, to ensure we are on the same page.
https://github.com/ToolsForDevs/FAST-SDK-Android/wiki/First-steps

**Comment by rushabh13** [comment]
@jonathangerbaud, I agree with @rikinindianic.

I have followed all your steps which are mentioned in https://github.com/ToolsForDevs/FAST-SDK-Android/wiki/First-steps

But I am only getting error in Logcat is "No keystore received. Please setup or check your api key in your build.gradle".

**Note**: I have also added my application to your companion application and updated the Hash key.

**Comment by jonathangerbaud** [comment]
@rikinindianic @rushabh13 Alright, let me test a few things.

Which version of gradle/Android Studio are you using ?

Also, when you are syncing gradle, does the Build/Sync panel mentions an error (at the top of the logs?)

**Comment by rikinindianic** [comment]
Here are the details,

Android gradle plugin: 3.5.3
Gradle version: 5.4.1
Android studio: 3.5.3

Also, no error found while syncing the gradle

**Comment by jonathangerbaud** [comment]
OK, well, I'm going to push a demo project on this repo so that you can clone it and test it. You'll just have to replace your api key.

If it doesn't work for you, then it means there's definitely something wrong on my end.

Give me an hour or two.

**Comment by jonathangerbaud** [comment]
Alright, I've pushed a quick demo project. Can you test it please and tell me if it's working or if you still have an error message?

**Comment by rikinindianic** [comment]
Hi @jonathangerbaud,

I got the same error in logcat, "No keystore received. Please setup or check your api key in your build.gradle".

I have just downloaded you demo project and replace the "YOU_API_KEY_HERE" with my key in build.gradle file, and then just run the project. I have also make sure the companion app is installed and the hash is updated.

So, it seems the problem is somewhere there either in the steps metioned to be followed for integration or in the library itself.

I also whant to know that the same demo is working at your side or not, have you tried integrating the fast sdk in any demo project?

**Comment by jonathangerbaud** [comment]
OK. Can you tell me which account (email address) are you using? So that I can try to figure out what's wrong.

**Comment by rikinindianic** [comment]
I have enrol my account under following offer, "SPECIAL OFFER FOR THE FIRST 50 BETA TESTERS".

**Comment by jonathangerbaud** [comment]
Yes, Yes, I know. But I need to know your account in order to be able to replicate your case. And in order to identify your account, I need the email address you have registered with (or your name in you don't want to disclose your email address).

**Comment by rikinindianic** [comment]
You can find my account by the name: Rikin Prajapati

**Comment by jonathangerbaud** [comment]
Ok found you, thanks. Quick question: are you on Windows or Mac ? (or maybe some other OS)

**Comment by rikinindianic** [comment]
Ubuntu 18.04.4 LTS (64-bit)

**Comment by jonathangerbaud** [comment]
So my guess is that there is a bug in the Gradle plugin, and that is affecting Unix systems (I only have Windows). And because of this bug, the class used under the hood by FAST is not generated, and you get the "no keystore error" in the Logcat.

So I pushed a new version of the Gradle plugin, 0.9.3, hoping that it will solve the issue. I've also added a bunch of logs to pinpoint the problem is this version doesn't fix the issue.

Please test version 0.9.3 and let me know if there any logs in the build panel during Gradle sync and builds.

**Comment by rikinindianic** [comment]
Plugin 0.9.3 also not working and no logs in gradle panel during sync process.

**Comment by jonathangerbaud** [comment]
Errr....

Do you see `fastsdk/data.json` and `generated/source/fast/classes/debug/com.toolsfordevs.fast.core.internal/KeystoreHolder.java` in your build folder?

**Comment by rikinindianic** [comment]
Yes both the files are generated under build folder as per your mentioned path but just look into the path specifically the **debug** folder (there are two variants) for the second one KeystoreHolder.java.

 
![Screenshot from 2020-02-13 19-05-18](https://user-images.githubusercontent.com/51501439/74440470-16087200-4e94-11ea-9500-b70680e52812.png)

**Comment by jonathangerbaud** [comment]
OK, I can see that the KeystoreHolder class is not in the "debug" folder but in the "debug." folder. That's why it doesn't work. 

There must be another glitch in the Gradle plugin, I'm going to check this out.

**Comment by jonathangerbaud** [comment]
Alright, found this useless dot, pushed new Gradle plugin version 0.9.4. I hope this fixes the issue.

**Comment by rikinindianic** [comment]
Finally....! 

The issue is fixed now, The logcat error is gone and I can see the success (SDK Initialized.) message instead and launching the fast is also working by using `Fast.launch(this)`

The problem is fixed with the new plugin (project level gradle file)

`        classpath 'gradle.plugin.com.toolsfordevs:fast:0.9.4'
`

So, Here I'm closing this issue.

**Comment by jonathangerbaud** [comment]
@rikinindianic Thanks for your help! Glad to know it's now working.
